{
 "title": "basic-monitor",
 "time": { "from": "now-15m", "to": "now-1m" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "rate", "query": "1m,5m,10m,30m," },
   {
    "name": "job",
    "query": "label_values(flask_exporter_info, job)"
   }
  ]
 },
 "panels": [
  {
   "title": "Request Total",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(job, status) (rate(flask_http_request_total{job=\"$job\"}[$rate]))",
     "legendFormat": "app: {{job}} status: {{status}}"
    }
   ]
  },
  {
   "title": "Request Success Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by(job) (rate(flask_http_request_total{job=\"$job\", status!~\"[5]..\"}[$rate]))/sum by(job) (rate(flask_http_request_total{job=\"$job\"}[$rate]))",
     "legendFormat": "app: {{job}}"
    }
   ]
  },
  {
   "title": "Requests Duration (Latency)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(flask_http_request_duration_seconds_bucket{job=\"$job\"}[$rate])) by (le)) ",
     "legendFormat": "P99$job"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(flask_http_request_duration_seconds_bucket{job=\"$job\"}[$rate])) by (le)) ",
     "legendFormat": "P95$job"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(flask_http_request_duration_seconds_bucket{job=\"$job\"}[$rate])) by (le)) ",
     "legendFormat": "P90$job"
    }
   ]
  },
  {
   "title": "Requests Error",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(job, status) (rate(flask_http_request_total{job=\"$job\", status=~\"[5]..\"}[$rate]))",
     "legendFormat": "app: {{job}} status: {{status}}"
    }
   ]
  }
 ]
}